services:
  postgres:
    image: postgres:14-alpine
    container_name: atlas-postgres-dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: roshan
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - roshan_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  roshan_postgres_data:
